### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by elmistooo** [volom/Telegram_Scraper_Sender#1]
mass_sender not work

**Comment by volom** [comment]
> mass_sender not work

What kind of error did you get? Please, give me the description of it

**Comment by elmistooo** [comment]
![image](https://user-images.githubusercontent.com/102189378/160298842-2ffce707-6a7d-4d04-bd5e-a4d5e53dde0c.png)

**Comment by volom** [comment]
> ![image](https://user-images.githubusercontent.com/102189378/160298842-2ffce707-6a7d-4d04-bd5e-a4d5e53dde0c.png)

It seems like you have a problem with the encoding of the content in your members.csv file. Try to set encoding manually with open('members.csv', 'r', **encoding='utf-8'**) (you may try any: "utf-8", "cp1251", "ascii" etc.). 

The problem may be that there are smileys in your file and that your system does not support reading them. Try to delete all names that contain smiles and try again. Otherwise, It may be the solution to read the smiley for your system
